### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by anteksiler** [jmar777/kwicks#1]
I would love to see the kwicks slider responsive.

**Comment by jmar777** [comment]
By responsive do you mean allowing everything to sized as a percentage of the container?

**Comment by anteksiler** [comment]
Yes, and maybe on mobile devices, it will become a normal finger-friendly horizontal slider.

**Comment by Duke3D** [comment]
+1 on the idea that the container scales up from a min-width to fill (a %age of) its surrounding container.  
(As for mobile, I'm happy to roll my own using a media query to substitute display method.)

**Comment by umit86** [comment]
Hey, is there a method to update the slider?

**Comment by SalonGuru** [comment]
We have a responsive implementation here - http://host3.salonguru.net/spoilmehair/

basically calculate the new single image width by dividing the overall width by the number of images (5 in our case) and re-initiaise. 

```
var newWidth = ($('.row2').width())/5;
$('.kwicks').kwicks({
    size: newWidth,
    maxSize : 336,
    spacing : 0,
    behavior: 'menu'
});

$(window).resize(function() {
    newWidth = ($('.row2').width())/5;
    $('.kwicks').kwicks({
        size: newWidth,
        maxSize : 336,
        spacing : 0,
        behavior: 'menu'
    });
});
```

**Comment by jmar777** [comment]
Alright - v2.1.0 is out with responsive layout.  Panels will expand as needed to fill the container, and the `minSize` and `maxSize` options can now be specified as a percentage.  Thanks for the feedback and suggestions, everyone!
