### ISSUE TITLE
Animation Timing

### ISSUE THREAD

**Issue by mherrington** [jmar777/kwicks#12]
Hi, this is a great plugin!

I've been able to update it to meet 99% of my needs, but as a novice, I'm looking to make a change to the slideshow settings. I hope I can explain what it is I'm looking to do clearly enough. 

Currently, it expands from one item to the next, which is what I want... however, I've added the functionality of the slideshow to the "active-expanded-classes.html" file and would like it to behave such as when an item is expanded (through hovering), it changes the order the next slide expanded in the list, rather than going back to where it was in the slide display order. i.e. so if the slider starts at 1, but the user hovers over 4, I'd like it so that the next item expanded is 5, not 2 as set by default.

Do you have any direction you could give me to change these settings?

Thanks!
Michelle

**Comment by jmar777** [comment]
Hey, sorry for the ridiculously long delay in replying.  I realize this is probably too late to be helpful at this point, but are you still having any issues I can help with?
