### ISSUE TITLE
Feature request: DelayMouseIn, DelayMouseOut

### ISSUE THREAD

**Issue by bongobongo** [jmar777/kwicks#15]
When moving the mousepointer over the kwicks element, It would be great to be able to set a delay i milliseconds. Could be good to have different delay for mouse in movement and mouse out movement.

This delay should affect how long it takes before the element do what it should do, when you mouse into an element.

Same for when mousing out of an element...

**Comment by jmar777** [comment]
+1, good idea. This can be implemented already through the API and doing your own delay logic, but this seems general enough that an out-of-the-box behavior could perhaps support it.

**Comment by bongobongo** [comment]
Do you have any plans for when to implement this feature as a out-of-the-box behaviour, e.g. settable using API variable? 

One other thing: I currently use 1.5 version ...
Do you have some example code on how I could do this using the 1.5 version, using the existing API? 

I also came across this plugin: hoverIntent when searching for how to do what I want here... maybe that could be usable as an extra option .... 
http://cherne.net/brian/resources/jquery.hoverIntent.html

**Comment by jmar777** [comment]
Hey, somehow missed that you had replied to this. Well, 1.5 is pretty ancient and it doesn't actually expose an API. If you're able to, I strongly recommend upgrading.  I'm planning on adding some support for customizable behavior like what you're suggesting in the v2.2.0 release.

**Comment by jmar777** [comment]
Alright, v2.2.0 is out with a lot of updates, including `delayMouseIn` and `delayMouseOut` options for the menu behavior.  The [home page](http://devsmash.com/projects/kwicks) has a rundown of everything that's new/changed.
