### ISSUE TITLE
Can I get it to display images?

### ISSUE THREAD

**Issue by Surrcon** [jmar777/kwicks#16]
When I have kwicks locally it works with images but when I use it on the web it only displays the first image and not the rest of them.  When I just leave it with the background colors that were already set up then it works on the web.  So how can I get kwicks to display images on the web and not just the background colors?

**Comment by jmar777** [comment]
Hey, sorry for the ridiculously long delay in replying.  I realize this is probably too late to be helpful at this point, but are you still having any issues I can help with?
