### ISSUE TITLE
remove click event

### ISSUE THREAD

**Issue by rob-kingsbury** [jmar777/kwicks#17]
I really only require the hover effect and having a pane stuck open when a user clicks on it gets unsightly for my purposes. How would I go about removing the click or selected event altogether?

**Comment by jmar777** [comment]
Hey - sorry for the long delay here.  I realize this is probably too late to be helpful at this point, but in case anyone else finds this the solution is to simply not use the built-in 'menu' behavior.  Kwicks provides an API for controlling the panels if you want custom behavior, so you could simply do something like:

```
$('#kwicks-container').on('mouseleave', function() {
    $(this).kwicks('expand', -1);
}).children().on('mouseover', function() {
    $(this).kwicks('expand');
})
```
