### ISSUE TITLE
iPad display issue

### ISSUE THREAD

**Issue by ghost** [jmar777/kwicks#18]
http://host3.salonguru.net/spoilmehair/

We're using the slideshow here and on desktop it works fine on all browser sizes.
On iPad Mini the surrounding div moves but the image doesn't
Don't know what happens on full size ipad

**Comment by jmar777** [comment]
Hey - sorry for the long delay here.  I'm trying to play catchup on GitHub issues now though.  Is there still an outstanding issue here?

**Comment by SalonGuru** [comment]
No, we had to abandon that approach and used a different carousel on the ipad/iphone

**Comment by jmar777** [comment]
K - sorry again for not getting back to you in time to be useful :\
