### ISSUE TITLE
Trigger event when expanding comes to original situation

### ISSUE THREAD

**Issue by augnustin** [jmar777/kwicks#19]
I use : 
        $('.kwicks').on('expand.kwicks', function(e, data) {
                  // action
                }

But I'd like to have a 
        $('.kwicks').on('reduce.kwicks', function(e, data) {
                  // action
                }

that triggers when the mouse leaves the whole kwicks and the columns come back to their original position.

**Comment by jmar777** [comment]
+1

Would make sense to be able to react to expand start, expand complete, collapse start, and collapse complete at a panel level.  At the container level you can already detect what you're asking for at the start of the animation, but not at the end:

``` javascript
$('.kwicks').on('expand.kwicks', function(e, data) {
    if (data.index === -1) {
        // when index === -1, then no panels are selected
    }
});
```

But there's currently no `expand-complete` type event.  You could always do a setTimeout with the animation duration, but then you'd have to clear it if another panel got expanded before the duration was complete.  I'll plan on a solution for this in a v2.2.0 release.

**Comment by jmar777** [comment]
Alright, v2.2.0 is out with a lot of updates, including an `expand-complete` event.  You can now use this to accomplish what you were requesting:

``` javascript
$('.kwicks').on('expand-complete', function(e, data) {
    if (!data.expanded) {
        // all panels are back in their default state
    }
});
```

The [home page](http://devsmash.com/projects/kwicks) has a rundown of everything that's new/changed.

**Comment by augnustin** [comment]
:+1:
