### ISSUE TITLE
Feature request: Completed

### ISSUE THREAD

**Issue by Upland** [jmar777/kwicks#21]
Would be good to know when the sliding animation is completed.

For example:

``` javascript
$(container).on('completed.kwicks', function(e, data) {
    if (data.index === 3) {
        $(content).fadeIn();
    }
});
```

At the very end of the kwicks plugin code there is:

``` javascript
  complete:  function() {
    self.isAnimated = false;
      alert('finished');                //   <<<---- works perfectly!
  }
```

But I am not skilled enough to know how to expose this in the way I need for it to be useful.

Thanks

**Comment by Duke3D** [comment]
the function is named "complete" not "completed"  try again with the typo fixed.
Not sure what $(content) will select to do a fadeIn on - have you defined what object "content" refers to?  
Usually you put an element selector there like $(".content") to grab the element with class = "content".
Or paste your code in the file in place of the alert.

Either way I'm not sure why you submitted a feature request to change the software - as you noted, the feature works perfectly.

**Comment by Upland** [comment]
Thanks for the reply but I think there is some basic misunderstanding here ...
1. my "completed" was a 'for example' ... ie. pseudo code ... how I would like it to work. It is **not** a typo.
2. yes, my alert() works perfectly but _only_ if I insert it into the plugin source code and want to know when **any** slider has completed ... it does not give me a way to know _which_ slider index was clicked - in the style of selected / expand on the kwicks examples page.
3. again, my "content" was part of pseudo code - I was trying to follow the style of the examples in the code on the examples page (that actually uses 'container' - so yes, this could be called a typo).

Hope this makes it clearer.

**Comment by jmar777** [comment]
This sounds pretty good to me, with some slight modifications:

Currently we just have `expand.kwicks` and `select.kwicks`.  There have been several requests for a `collapse.kwicks` event as well (which would also suggest there should be an `unselect.kwicks`).  As this issue points out, it's also useful to know when the animations have completed, so what are your thoughts on the following?
- `expand.kwicks`: Fired when a panel begins to expand.
- `expand-complete.kwicks`: Fired when a panel is fully expanded (but _not_ fired if another panel is expanded prior to the animation completing).
- `collapse.kwicks`: Fired when a panel begins to collapse.
- `collapse-complete.kwicks`: Fired when a panel is fully collapsed (but _not_ fired if it is re-expanded prior to the animation completing).
- `select.kwicks`: Fired when a panel is selected (selection is about state, not about the expand/collapse/animation/etc, so no `select-complete` event).
- `unselect.kwicks`: Fired when another panel is selected (or no panels at all selected).

Would we still be missing anything obvious?

**Comment by Upland** [comment]
That sounds like a perfect synopsis! ... +1 for thinking about 're-expanded' etc ... that hadn't even occurred to me.

Can't think of anything obvious that's missing from the above.

Thanks

**Comment by jmar777** [comment]
Alright, v2.2.0 is out with a lot of updates.  I ended up going a different direction than what we discussed above, because it was simply too "spammy" from an events perspective.  The new version does, however, add an `expand-complete` event, as well as a lot of useful information in the event data objects.  The new system should allow you to react to virtually any different state of the plugin.  Please note that this is a breaking change with regards to the old events API - the [home page](http://devsmash.com/projects/kwicks) has a rundown of everything that's new/changed.

Please let me know if you find it to still be deficient for any of your use cases!
