### ISSUE TITLE
How to best select kwicks that are not open

### ISSUE THREAD

**Issue by jrdn91** [jmar777/kwicks#26]
What is the best solution for selecting kwicks that are not open. For instance when I hover over one I want to grab all the other kwicks and do something with them in jquery.

**Comment by jmar777** [comment]
Something like this should work:

```
$('.kwicks').children().on('expand', function() {
    var $expanded = $(this),
        $others = $expanded.siblings();
});
```

Let me know if that works for you!

**Comment by jrdn91** [comment]
this isn't working.

the page I'm working with is at fotype.com/chosen-conference

When you click on the speakers, and they slide out, when the user hovers over one, I want to grab those little name circle images (class of name) and fade the ones that are not open out. Then fade them back in when none of them are open.

**Comment by jmar777** [comment]
I'm unable to find the speakers page (or anything clickable on the page you linked to).

Small world moment, though: Seacoast Church where the conference is being held is just about 5 minutes from my office.

**Comment by jrdn91** [comment]
Dude that's insane! Ever since I've moved here it's felt like a small world.

Any who we'e been pushing this for some time today so it's possible you caught it in between iterations.

[http://fotype.com/chosen-conference/]

I'm going to try getting it in there again right now and see if maybe I was just doing it wrong before.

**Comment by jmar777** [comment]
Ahh, I can see them now.  Try something like this:

``` javascript
$('.kwicks').on('expand.kwicks', function(e, data) {
    var $container = $(this);
    if (data.index === -1) {
        // everything is collapsed
        $container.find('.name').stop().fadeIn();
    } else {
        var $expanded = $container.children().eq(data.index),
            $others = $expanded.siblings();
        $expanded.find('.name').stop().fadeIn();
        $others.find('.name').stop().fadeOut();
    }
});
```

**Comment by jrdn91** [comment]
Hmm I'm just not having any luck with this, and I can't place it outside of the function that initiates the hover actions because the on('expand') fires before any expansion correct? I've got it right after the hover function outside of it

**Comment by jmar777** [comment]
Just took another peek and am noticing a couple issues.

First, it looks like you're instantiating the kwicks plugin over and over and over again.  You can start to observe this if you do a `console.log('expanded!')` in the `expand.kwicks` event handler.  Notice that as you move the mouse around the vents starts firing repeatedly, even though the expanded panel isn't changing.  Haven't dug in further than that, but fixing that would be my first priority.

Second, it looks like there may be some timing issues (perhaps related to the above) with regards to when you're instantiating the kwicks plugin and when you're binding the events.  You might be better off using event delegation instead, just to ensure there aren't any timing issues with the event binding:

``` javascript
$(document).on('expand.kwicks', '.kwicks', function(e, data) {
    var $container = $(this);
    if (data.index === -1) {
        // everything is collapsed
        $container.find('.name').stop().fadeIn();
    } else {
        var $expanded = $container.children().eq(data.index),
            $others = $expanded.siblings();
        $expanded.find('.name').stop().fadeIn();
        $others.find('.name').stop().fadeOut();
    }
});
```

I ran that in the console, and it was "doing something", but I believe the bigger issue mentioned further above was interfering with it.

**Comment by jmar777** [comment]
Any updates on this?

**Comment by jrdn91** [comment]
I haven't really come back to this, other project have picked up but when I get the chance to work on it again monday I'll be attempting to tie a few things up and try to get this working.

**Comment by jmar777** [comment]
Alright, I just pushed out v2.2.0 with some major updates to the events system.  You can now get access to collapsed panels within the `expand` event like this:

``` javascript
$('.kwicks').on('expand.kwicks', function(e, data) {
    console.log(data.collapsed);
});
```

Also, since you were dynamically setting up and tearing down Kwicks instances, you may find the new `$().kwicks('destroy')` method useful.  The [home page](http://devsmash.com/projects/kwicks) has a rundown of everything that's new/changed.
