### ISSUE TITLE
Trying to close all panels when clicking anywhere outside of the kwicks area

### ISSUE THREAD

**Issue by jrdn91** [jmar777/kwicks#27]
Here is the code I'm using to get this to work (working with an ipad)

```
$('.right-box').on('click', function(){
                $(this).kwicks('expand');
            });
            $('#left-area, nav').on('click', function(){
                var index = $('.kwicks').kwicks('expanded');

                if(index){
                    $('.kwicks').kwicks('expand', -1);
                }
            });
```

But when clicking the first item in the kwicks area, and then clicking off of it (ie. either inside the left area or the nav) it stays open, however, if any of the other kwicks areas are open and I click off of it (again either in the left area or the nav) they close just fine. Is there something wrong with the way I'm trying to get them to close? Or maybe an easier way to get this done on an ipad or touch device.

**Comment by jmar777** [comment]
Try using `if (index >= 0)` instead of `if (index)`.

If the first panel is expanded, then `index` will be `0`, and your condition won't pass.

**Comment by jrdn91** [comment]
that works thanks so much!
