### ISSUE TITLE
Open post/page/slide on click?

### ISSUE THREAD

**Issue by maky312** [jmar777/kwicks#30]
Hi guys,

is it possible to open link on click? there is no that option in slides. I have removed kwick-button and I need to open post on click, now nothing happens if you click on the image, please add this option, or some code/custom field if is possbile.

Thank you!

**Comment by jmar777** [comment]
Can you explain your exact scenario?  Kwicks doesn't prevent you from using `a` elements or setting you your click handlers on other types of elements.

**Comment by jmar777** [comment]
Were you able to resolve this issue?

**Comment by jmar777** [comment]
Closing due to lack of response.
