### ISSUE TITLE
Add Kwicks Horizontal to Wordpress

### ISSUE THREAD

**Issue by luckyrajiv** [jmar777/kwicks#32]
How can i add the Kwicks Slider to wordpress site ?

I tried many possible ways.

It shows the static slider. It doesn't move at all.

Please Help.

**Comment by jmar777** [comment]
Hey - I haven't actually worked directly with Wordpress, but I've seen others integrate Kwicks into Wordpress themes/templates.  If you're not seeing any of the Kwicks behavior there is likely a JavaScript error somewhere, a timing issue, or something along those lines.  Do you have a test site up I can view?

**Comment by jmar777** [comment]
Closing due to a lack of updates.
