### ISSUE TITLE
panels of varying widths (different min/max, full control of dimensions when expanded/collapsed)

### ISSUE THREAD

**Issue by vesper8** [jmar777/kwicks#34]
Hi there,

I found your plugin and so far I'm loving it. But I'm trying to do something specific with it that isn't shown in any of your examples. I've tried many tweaks but haven't been able to get it to function the way I want so far.. maybe it wasn't meant for this and I need to find that out asap because I'll need to either modify it or try another solution otherwise.

Basically I want to have 3 panels. Each panel has different min/max dimensions.

On load I'd want the 1st panel to be collapsed with a width of 20px, the 3rd panel expanded with a max width of 200px, and the middle panel would take up the entire remaining width. The 3 panels take up 100% of the page.

The 1st panel, when expanded would expand to 200px. The 3rd panel, when collapsed would collapse to 20px. And the middle panel would always take whatever is available.

Last complication is.. I want to be able to have all 3 panels "expanded" at the same time. So panel 1 and 3 at 200px and panel 2 taking the rest. Panel 2 is never collapsed.

Sounds complicated.. but is it doable with Kwicks? If so.. I'd love to see an example of this more advanced scenario. Or at least an example or explanation of how to have 3 panels that don't all behave the same as in all your examples.

Here's to hoping you can reply quickly and either help me or confirm that your plugin isn't meant/capable of this difficult setup.

Thanks a lot!

**Comment by jmar777** [comment]
Hey - just saw your issue, so I hope this is a fast enough response...

Unfortunately, Kwicks won't be able to handle the scenario you've describe.  It's been discussed as a feature at some point in the future, but at present it doesn't handle different min/max sizes on a panel-by-panel basis.  It also requires that zero or one panel be expanded at any given time (but never multiple panels).  Sorry it's not more helpful for your situation!

**Comment by vesper8** [comment]
Thanks for getting back to me. I ended up finding a question on
stackoverflow that was essentially asking for the same thing, and you had
replied saying it wasn't possible but you may add it in the future.. that
was a year ago I think. Anyway someone in that very same thread pointed out
a custom solution that I used to build something that accomplishes exactly
what I wanted so I'm good now. Thanks anyway though, I like your plugin and
may use it somewhere else if I get the chance. I'll be looking at your
suspend plugin too as I've recently started using node.

Cheers!

**Comment by jmar777** [comment]
Awesome, glad you found a working solution!  Let me know how suspend works out for you as well! I'm getting ready to push out a _major_ update to it in the next week or so, so keep an eye out for 0.4.0 :)
