### ISSUE TITLE
Add Collapse Method

### ISSUE THREAD

**Issue by cinnamonKale** [jmar777/kwicks#35]
There should be a method to collapse the panels of the accordion, to go along with the Expand method.

**Comment by jmar777** [comment]
You can collapse panels using `$(container).kwicks('expand', -1)`.  Does that work for you?

**Comment by jmar777** [comment]
I'm going to go ahead and close this due to lack of response, but feel free to re-open if you have any further issues!

**Comment by cinnamonKale** [comment]
Thank you, this worked!
