### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by guilmanu** [jmar777/kwicks#36]
Hi, checking if my website works fine on #browsers. Well, seems there's something wrong with IE 8 !  It works fine on all browsers on mac OS X (which I'm working with) + FF & Chrome (windows XP)

Is it a known issue ? (while kwicks is said to be IE7+ compatible)… Have I forgotten something ?
![kwicks](https://f.cloud.github.com/assets/6622841/2116752/913850a2-909b-11e3-9340-7a049db1a6fe.jpg)

**Comment by jmar777** [comment]
Hey - so sorry for the delayed reply on this, I missed it earlier!  I'm not set up to test IE8 right now, but I can try and take a look at this on Monday.  Can you provide a link to an example page with this behavior (if you're still having issues with it)?

**Comment by guilmanu** [comment]
My turn to be sorry. It does run OK for IE8. Seems there was a conflict with other scripts usingjquery. Solved them and kwicks runes fine. I should have told you. Sorry !

**Comment by jmar777** [comment]
No problem at all, glad it's working!  I'm going to go ahead and close this, but feel free to re-open (or create a new issue) if you have any further problems.
