### ISSUE TITLE
IE7 and IE8 Issues

### ISSUE THREAD

**Issue by hojae8484** [jmar777/kwicks#39]
Using kwicks plug-in, i made a navigation menu bar.

check 'www.rocknfresh.com'

It should be worked as horizontal but i see vertical on ie7 and 8

btw it works fine on chrome and fire fox

**Comment by jmar777** [comment]
I just pulled it up in IE8, and it appeared to work correctly.  The links did stack vertically _before_ the plugin was initialized, but then rendered correctly once it had a chance to run.  Is that the same behavior you were seeing?

To avoid that behavior, I recommend styling the links with CSS as well, to make sure that they look correct even before the plugin has initialized.  See the CSS on the [horizontal kwicks example](http://devsmash.com/projects/kwicks/2.2.x/examples/horizontal) for an example of how to avoid that initial page jitter.

**Comment by hojae8484** [comment]
Thx man. It helped alot.
Since i got 7 navigation button(can't divide into 7 perfectly. i just did it like 14%), 
i couldnt stop that page jitter but it dosent stuck vertically anymore.
I really appreciate that:)

By the way, in 1150px; i should just write down 

width: 14%? or is there any other way that i can divide 1150px perfectly?

**Comment by jmar777** [comment]
Hey - sorry for the long (looooong) delay here. This issue fell off my radar. Given that this goes back to March, I'm going to assume you made it past this... please feel free to re-open if you still need anything (and I'll do my best to be more responsive!).
