### ISSUE TITLE
Slider with multiple elements?

### ISSUE THREAD

**Issue by dantnan** [jmar777/kwicks#42]
Is there a way to make it as a slider with multiple elements but for instance i want to make it show 5 elements and add buttons "next" and "preview" and when i click on them the other elements will come?

Thanks in advance.

**Comment by jmar777** [comment]
@dantnan If I understand you correctly, then you no - not with kwicks by itself.

It almost sounds like you want a carousel where each panel has an instance of kwicks inside of it. Does that sound accurate?

**Comment by dantnan** [comment]
@jmar777  thanks for your reply. Yes that is exactly what i want to achieve. How can i make that? Thanks in advance

**Comment by jmar777** [comment]
@dantnan Hey - sorry I never saw your reply on this (pretty sure my notifications aren't working right...).  I'm doing some story cleanup right now, but please feel free to re-open this if you're still bumping into anything kwicks related.
