### ISSUE TITLE
Webpage 400 Error

### ISSUE THREAD

**Issue by jCrip** [jmar777/kwicks#47]
Hi, i'm trying to go to the website for the documentation but i get a 400 error. 

Anything on that? Other source for the documentation?

I love this plugin!!!!

jCrip

**Comment by jmar777** [comment]
Hey - thank you _so much_ for filing this issue. I'm presently out of the country and had no idea that that the site had been down for 10 days (!!) due to a billing snafu with my hosting provider.  Everything should be sorted now, though.  Thanks again, really appreciate it!
