### ISSUE TITLE
Kwicks in Wordpress

### ISSUE THREAD

**Issue by coyabagroup** [jmar777/kwicks#5]
Love the script. I would like to use this in a Wordpress setting where I can have a featured image(s) on the frontpage respond according to the script I would implement - such as the easing example. Does anyone know the best way to get this done?

**Comment by jmar777** [comment]
Hey, sorry for the incredibly long delay in getting back to you on this. I'm not sure I actually understand what you're going for here, though.  Can you expand a bit?

**Comment by coyabagroup** [comment]
I was curious to know if someone had already set this up as a wordpress
plugin. If not, have you ever incorporated this into a wordpress theme and
how did you go about doing it?

Thanks

**Comment by jmar777** [comment]
I've never done any Wordpress development, so I wouldn't know what direction to point you in.  There is [this post](http://www.paddsolutions.com/how-to-integrate-accordion-image-slider-to-a-wordpress-theme/), but it's pretty old and based on an old version of Kwicks. May still be helpful nonetheless, though.

**Comment by jmar777** [comment]
I'm going to go ahead and close out this issue since it doesn't seem to be an actual problem with Kwicks, but please feel free to post any followup comments if you need any Kwicks-specific advice.

**Comment by coyabagroup** [comment]
Yes thanks for your help with it.Adria.Sent from Samsung Mobile 

 Jeremy Martin  wrote: 

I'm going to go ahead and close out this issue since it doesn't seem to be an actual problem with Kwicks, but please feel free to post any followup comments if you need any Kwicks-specific advice.

```
          —
          Reply to this email directly or view it on GitHub.
```
