### ISSUE TITLE
Multiple instances of Kwicks on the same page?

### ISSUE THREAD

**Issue by John31** [jmar777/kwicks#7]
Hi,

Is there a way to implement multiple instances of Kwicks on the same page?
I was tying something like this but it's not working:

<script type='text/javascript'>
    $(function() {
        $('.kwicks','.kwicks2').kwicks({
            size: 64,
            maxSize : 310,
            spacing : 0,
            duration: 300,
            behavior: 'menu'
        });
    });
</script>

Thanks in advance!
Best regards,
John

**Comment by jmar777** [comment]
Hey John - I think the issue you have is with your selector string.  Try changing this...

`$('.kwicks','.kwicks2').kwicks(...);`

... to this...

`$('.kwicks, .kwicks2').kwicks(...);`

The problem with the first one is that you're passing two parameters to `$()`, which causes the second one to be interpreted as a "context" argument... which I don't think strings are valid for, anyway.

Also, here's a jsfiddle demonstrating multiple kwicks instances on the same page: http://jsfiddle.net/zLrHg/

**Comment by John31** [comment]
My javascript knowledge is equal to 0 but it's never to late to learn new stuff.
Many thanks for the example and the explanation. I've learned a new thing today! :)

I think the example of multiple kwicks instances on the same page could be also placed on http://devsmash.com/projects/kwicks in the Examples section.

Thanks again!
Best regards,
John

**Comment by jmar777** [comment]
Glad that helped, John.  I've got a few updates planned for the plugin a well as the documentation, so I'll definitely add your suggestion to the todo list!
