### ISSUE TITLE
Open only on click

### ISSUE THREAD

**Issue by najdias** [jmar777/kwicks#8]
This is more a request than a issue.
I want to request if you can add the funtionality to open a slide only if clicked and not on mouse over.

**Comment by jmar777** [comment]
Good news, this is already supported :)

Instead of using the pre-canned `behavior: 'menu'` option, simply wire up the click event yourself and use the `.kwicks('expand')` method.  E.g.,

``` javascript
$('.kwicks').kwicks({
    size: 125,
    maxSize : 250,
    spacing : 5
}).children().click(function() {
    // expand the panel when it's clicked
    $(this).kwicks('expand');
});
```

Here's a working example: http://jsfiddle.net/b4VxZ/

Hope that helps!

**Comment by jmar777** [comment]
As a side note, I _really_ need to add an example of this in the docs, since it's a commonly asked question...

**Comment by najdias** [comment]
Hello jmar777 that is what i was looking for. Thank you very much.

**Comment by gokhan214** [comment]
Hi jmar777 , i love your script and i allready created an expanding full screen one onclick but all i need to know is, is there a possiblity of collapsing on another click on an expanded item? any help appreciated thank you so much
